#!/bin/bash
#
# Creates Rest cluster with 1 master N slave config
# Usage: redis_startup [clusterSize] [password]

clusterSize=$1
password=$2

/usr/bin/wget -N -P /etc/redis/ https://raw.githubusercontent.com/aweris/core-os/master/redis/conf/redis-master.conf

echo '\nrequirepass ' $password >> /etc/redis/redis-master.conf

/usr/bin/wget -N -P /etc/redis/ https://raw.githubusercontent.com/aweris/core-os/master/redis/conf/redis-slave.conf

echo '\nrequirepass ' $password >> /etc/redis/redis-slave.conf
echo '\nmasterauth ' $password >> /etc/redis/redis-slave.conf

mkdir -p /opt/services/templates
mkdir -p /opt/services/instances

/usr/bin/wget -N -P /opt/services/instances https://raw.githubusercontent.com/aweris/core-os/master/redis/redis@1.service

/usr/bin/wget -N -P /opt/services/templates https://raw.githubusercontent.com/aweris/core-os/master/redis/redis@.service

if [ $clusterSize -gt 1 ]
then
    for i in {2..$clusterSize}
    do
       instance='/opt/services/instances/redis@'$i'.service'
       ln -s /opt/services/templates/redis@.service $instance
       echo $instance ' created'
    done
fi

fleetctl start /opt/services/instances/redis@{1..$clusterSize}.service