#!/bin/bash
#
# Creates Rest cluster with 1 master N slave config
# Usage: redis_startup [clusterSize] [password]

clusterSize=$1
password=$2

echo "Creating Redis Cluster with $clusterSize nodes"

/usr/bin/wget -N -P /etc/redis/ https://raw.githubusercontent.com/aweris/core-os/master/redis/conf/redis-master.conf

echo -e '\n' >> /etc/redis/redis-master.conf
echo -e 'requirepass ' $password >> /etc/redis/redis-master.conf

/usr/bin/wget -N -P /etc/redis/ https://raw.githubusercontent.com/aweris/core-os/master/redis/conf/redis-slave.conf

echo -e '\n' >> /etc/redis/redis-slave.conf
echo -e 'requirepass ' $password >> /etc/redis/redis-slave.conf
echo -e 'masterauth ' $password >> /etc/redis/redis-slave.conf

mkdir -p /opt/services/templates
mkdir -p /opt/services/instances

/usr/bin/wget -N -P /opt/services/instances https://raw.githubusercontent.com/aweris/core-os/master/redis/redis@1.service

/usr/bin/wget -N -P /opt/services/templates https://raw.githubusercontent.com/aweris/core-os/master/redis/redis@.service

if [ $clusterSize -gt 1 ]
then
   for i in $(seq 2 $clusterSize)
    do
       instance='/opt/services/instances/redis@'$i'.service'
       ln -s /opt/services/templates/redis@.service $instance
    done
fi

fleetctl start /opt/services/instances/redis@*.service