#!/bin/bash
#
dockerPort=$1

/usr/bin/docker run -d --name swarm-manager --net=host swarm:latest manage etcd://127.0.0.1:2379
/usr/bin/docker run -d --name swarm-agent --net=host swarm:latest join --addr=$(COREOS_PUBLIC_IPV4):$1 etcd://127.0.0.1:2379

docker -H :4000 info